name: MCPVots Codespace Environment Check

on:
  push:
    branches: [ clean-main ]
    paths:
      - '.devcontainer/**'
      - 'advanced_ai_modules/**'
      - 'package.json'
  pull_request:
    branches: [ clean-main ]
    paths:
      - '.devcontainer/**'
      - 'advanced_ai_modules/**'
      - 'package.json'
  workflow_dispatch:

jobs:
  test-devcontainer:
    runs-on: ubuntu-latest
    name: Test Development Container Configuration
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Validate devcontainer.json
      run: |
        echo "🔍 Validating devcontainer.json syntax..."
        cat .devcontainer/devcontainer.json | jq empty
        echo "✅ devcontainer.json is valid JSON"
        
    - name: Check Dockerfile syntax
      run: |
        echo "🔍 Validating Dockerfile syntax..."
        docker run --rm -i hadolint/hadolint < .devcontainer/Dockerfile || true
        echo "✅ Dockerfile syntax checked"
        
    - name: Install dependencies
      run: |
        npm ci
        
    - name: Test AI modules structure
      run: |
        echo "🧠 Checking Advanced AI Modules structure..."
        if [ -d "advanced_ai_modules" ]; then
          echo "✅ advanced_ai_modules directory exists"
          find advanced_ai_modules -name "*.py" | head -10
          echo "✅ Python files found in AI modules"
        else
          echo "❌ advanced_ai_modules directory missing"
          exit 1
        fi
        
    - name: Test npm scripts
      run: |
        echo "🔧 Testing npm scripts..."
        npm run type-check || echo "⚠️ Type check skipped"
        echo "✅ Build scripts validated"
        
    - name: Check port configuration
      run: |
        echo "🔌 Checking port forwarding configuration..."
        grep -o '"[0-9]\{4\}"' .devcontainer/devcontainer.json | sort -u | wc -l
        echo "✅ Port configuration checked"
        
  test-ai-modules:
    runs-on: ubuntu-latest
    name: Test Advanced AI Modules
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy pandas asyncio aiohttp fastapi pytest pytest-asyncio
        
    - name: Test AI module imports
      run: |
        echo "🧠 Testing AI module structure..."
        cd advanced_ai_modules
        python -c "
        import sys
        import os
        sys.path.append('.')
        
        # Test module structure
        modules = ['quantum_strategy', 'neural_meta_learning', 'distributed_swarm', 
                  'temporal_knowledge_graph', 'self_modifying_code', 'autonomous_orchestrator']
        
        for module in modules:
            if os.path.exists(f'{module}/__init__.py'):
                print(f'✅ {module} module structure valid')
            else:
                print(f'❌ {module} module missing __init__.py')
                sys.exit(1)
        
        print('✅ All AI modules have proper structure')
        "
        
    - name: Test module syntax
      run: |
        echo "🔍 Checking Python syntax in AI modules..."
        find advanced_ai_modules -name "*.py" -exec python -m py_compile {} \; || echo "⚠️ Some syntax issues found but continuing"
        echo "✅ Python syntax check completed"
        
  prebuild-test:
    runs-on: ubuntu-latest
    name: Test Prebuild Configuration
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Test Docker build context
      run: |
        echo "🏗️ Testing Docker build context..."
        docker build -f .devcontainer/Dockerfile -t mcpvots-test . --dry-run || true
        echo "✅ Docker build context validated"
        
    - name: Check setup script
      run: |
        echo "🔧 Validating setup script..."
        chmod +x .devcontainer/setup.sh
        bash -n .devcontainer/setup.sh
        echo "✅ Setup script syntax valid"
        
    - name: Validate environment variables
      run: |
        echo "🌍 Checking environment configuration..."
        if [ -f ".env.example" ]; then
          echo "✅ Environment example found"
        else
          echo "⚠️ Consider adding .env.example file"
        fi
        
  documentation-check:
    runs-on: ubuntu-latest
    name: Validate Documentation
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Check documentation files
      run: |
        echo "📚 Checking documentation..."
        docs_files=(
          "README.md"
          ".github/CODESPACE_SETUP.md"
          "advanced_ai_modules/INTEGRATION_GUIDE.md"
          "CLEANUP_COMPLETE.md"
        )
        
        for file in "${docs_files[@]}"; do
          if [ -f "$file" ]; then
            echo "✅ $file exists"
          else
            echo "❌ $file missing"
            exit 1
          fi
        done
        
    - name: Check npm scripts documentation
      run: |
        echo "🔧 Checking npm scripts in package.json..."
        ai_scripts=$(grep -c "ai:" package.json || echo 0)
        if [ "$ai_scripts" -gt 5 ]; then
          echo "✅ AI module scripts found: $ai_scripts"
        else
          echo "❌ Not enough AI module scripts found"
          exit 1
        fi
